\ font-vga-8x8.fs -- 8x8 bitmap font data for BasicForth.
\ require it for `text`; it pulls in fontcore.fs (the engine) and selects
\ itself.  GENERATED by tools/psf2font.py -- do not edit.
\
\ This file is GPL code plus public-domain data:
\
\   The Forth code (the require line and the selector word) is
\     Copyright (C) 2026 Brandon Blodget
\     SPDX-License-Identifier: GPL-2.0-only
\
\   The (vga-8x8) bitmap table is the IBM PC VGA 8x8 character-ROM font,
\   by way of the Linux console font collection.  Debian's
\   console-setup copyright states: "All console fonts are public
\   domain by nature."  The shapes date to the original IBM character
\   ROMs; no one claims them here.
\     SPDX-License-Identifier: LicenseRef-PublicDomain
\   Generated from Uni2-VGA8.psf.gz.

require fontcore.fs                          \ the text/glyph engine

\ 256 glyphs in CP437 order, 8 bytes each (MSB = leftmost
\ pixel) -- exactly what `stamp` reads.
create (vga-8x8)
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \   0 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \   1 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \   2 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \   3 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \   4 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \   5 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \   6 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \   7 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \   8 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \   9 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  10 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  11 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  12 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  13 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  14 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  15 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  16 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  17 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  18 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  19 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  20 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  21 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  22 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  23 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  24 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  25 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  26 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  27 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  28 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  29 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  30 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  31 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  32 SPC
  $18 c, $3c c, $3c c, $18 c, $18 c, $00 c, $18 c, $00 c,   \  33 !
  $66 c, $66 c, $24 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  34 "
  $6c c, $6c c, $fe c, $6c c, $fe c, $6c c, $6c c, $00 c,   \  35 #
  $18 c, $3e c, $60 c, $3c c, $06 c, $7c c, $18 c, $00 c,   \  36 $
  $00 c, $c6 c, $cc c, $18 c, $30 c, $66 c, $c6 c, $00 c,   \  37 %
  $38 c, $6c c, $38 c, $76 c, $dc c, $cc c, $76 c, $00 c,   \  38 &
  $18 c, $18 c, $30 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  39 '
  $0c c, $18 c, $30 c, $30 c, $30 c, $18 c, $0c c, $00 c,   \  40 (
  $30 c, $18 c, $0c c, $0c c, $0c c, $18 c, $30 c, $00 c,   \  41 )
  $00 c, $66 c, $3c c, $ff c, $3c c, $66 c, $00 c, $00 c,   \  42 *
  $00 c, $18 c, $18 c, $7e c, $18 c, $18 c, $00 c, $00 c,   \  43 +
  $00 c, $00 c, $00 c, $00 c, $00 c, $18 c, $18 c, $30 c,   \  44 ,
  $00 c, $00 c, $00 c, $7e c, $00 c, $00 c, $00 c, $00 c,   \  45 -
  $00 c, $00 c, $00 c, $00 c, $00 c, $18 c, $18 c, $00 c,   \  46 .
  $06 c, $0c c, $18 c, $30 c, $60 c, $c0 c, $80 c, $00 c,   \  47 /
  $38 c, $6c c, $c6 c, $d6 c, $c6 c, $6c c, $38 c, $00 c,   \  48 0
  $18 c, $38 c, $18 c, $18 c, $18 c, $18 c, $7e c, $00 c,   \  49 1
  $7c c, $c6 c, $06 c, $1c c, $30 c, $66 c, $fe c, $00 c,   \  50 2
  $7c c, $c6 c, $06 c, $3c c, $06 c, $c6 c, $7c c, $00 c,   \  51 3
  $1c c, $3c c, $6c c, $cc c, $fe c, $0c c, $1e c, $00 c,   \  52 4
  $fe c, $c0 c, $c0 c, $fc c, $06 c, $c6 c, $7c c, $00 c,   \  53 5
  $38 c, $60 c, $c0 c, $fc c, $c6 c, $c6 c, $7c c, $00 c,   \  54 6
  $fe c, $c6 c, $0c c, $18 c, $30 c, $30 c, $30 c, $00 c,   \  55 7
  $7c c, $c6 c, $c6 c, $7c c, $c6 c, $c6 c, $7c c, $00 c,   \  56 8
  $7c c, $c6 c, $c6 c, $7e c, $06 c, $0c c, $78 c, $00 c,   \  57 9
  $00 c, $18 c, $18 c, $00 c, $00 c, $18 c, $18 c, $00 c,   \  58 :
  $00 c, $18 c, $18 c, $00 c, $00 c, $18 c, $18 c, $30 c,   \  59 ;
  $06 c, $0c c, $18 c, $30 c, $18 c, $0c c, $06 c, $00 c,   \  60 <
  $00 c, $00 c, $7e c, $00 c, $00 c, $7e c, $00 c, $00 c,   \  61 =
  $60 c, $30 c, $18 c, $0c c, $18 c, $30 c, $60 c, $00 c,   \  62 >
  $7c c, $c6 c, $0c c, $18 c, $18 c, $00 c, $18 c, $00 c,   \  63 ?
  $7c c, $c6 c, $de c, $de c, $de c, $c0 c, $78 c, $00 c,   \  64 @
  $38 c, $6c c, $c6 c, $fe c, $c6 c, $c6 c, $c6 c, $00 c,   \  65 A
  $fc c, $66 c, $66 c, $7c c, $66 c, $66 c, $fc c, $00 c,   \  66 B
  $3c c, $66 c, $c0 c, $c0 c, $c0 c, $66 c, $3c c, $00 c,   \  67 C
  $f8 c, $6c c, $66 c, $66 c, $66 c, $6c c, $f8 c, $00 c,   \  68 D
  $fe c, $62 c, $68 c, $78 c, $68 c, $62 c, $fe c, $00 c,   \  69 E
  $fe c, $62 c, $68 c, $78 c, $68 c, $60 c, $f0 c, $00 c,   \  70 F
  $3c c, $66 c, $c0 c, $c0 c, $ce c, $66 c, $3a c, $00 c,   \  71 G
  $c6 c, $c6 c, $c6 c, $fe c, $c6 c, $c6 c, $c6 c, $00 c,   \  72 H
  $3c c, $18 c, $18 c, $18 c, $18 c, $18 c, $3c c, $00 c,   \  73 I
  $1e c, $0c c, $0c c, $0c c, $cc c, $cc c, $78 c, $00 c,   \  74 J
  $e6 c, $66 c, $6c c, $78 c, $6c c, $66 c, $e6 c, $00 c,   \  75 K
  $f0 c, $60 c, $60 c, $60 c, $62 c, $66 c, $fe c, $00 c,   \  76 L
  $c6 c, $ee c, $fe c, $fe c, $d6 c, $c6 c, $c6 c, $00 c,   \  77 M
  $c6 c, $e6 c, $f6 c, $de c, $ce c, $c6 c, $c6 c, $00 c,   \  78 N
  $7c c, $c6 c, $c6 c, $c6 c, $c6 c, $c6 c, $7c c, $00 c,   \  79 O
  $fc c, $66 c, $66 c, $7c c, $60 c, $60 c, $f0 c, $00 c,   \  80 P
  $7c c, $c6 c, $c6 c, $c6 c, $c6 c, $ce c, $7c c, $0e c,   \  81 Q
  $fc c, $66 c, $66 c, $7c c, $6c c, $66 c, $e6 c, $00 c,   \  82 R
  $3c c, $66 c, $30 c, $18 c, $0c c, $66 c, $3c c, $00 c,   \  83 S
  $7e c, $7e c, $5a c, $18 c, $18 c, $18 c, $3c c, $00 c,   \  84 T
  $c6 c, $c6 c, $c6 c, $c6 c, $c6 c, $c6 c, $7c c, $00 c,   \  85 U
  $c6 c, $c6 c, $c6 c, $c6 c, $c6 c, $6c c, $38 c, $00 c,   \  86 V
  $c6 c, $c6 c, $c6 c, $d6 c, $d6 c, $fe c, $6c c, $00 c,   \  87 W
  $c6 c, $c6 c, $6c c, $38 c, $6c c, $c6 c, $c6 c, $00 c,   \  88 X
  $66 c, $66 c, $66 c, $3c c, $18 c, $18 c, $3c c, $00 c,   \  89 Y
  $fe c, $c6 c, $8c c, $18 c, $32 c, $66 c, $fe c, $00 c,   \  90 Z
  $3c c, $30 c, $30 c, $30 c, $30 c, $30 c, $3c c, $00 c,   \  91 [
  $c0 c, $60 c, $30 c, $18 c, $0c c, $06 c, $02 c, $00 c,   \  92 \
  $3c c, $0c c, $0c c, $0c c, $0c c, $0c c, $3c c, $00 c,   \  93 ]
  $10 c, $38 c, $6c c, $c6 c, $00 c, $00 c, $00 c, $00 c,   \  94 ^
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $ff c,   \  95 _
  $30 c, $18 c, $0c c, $00 c, $00 c, $00 c, $00 c, $00 c,   \  96 `
  $00 c, $00 c, $78 c, $0c c, $7c c, $cc c, $76 c, $00 c,   \  97 a
  $e0 c, $60 c, $7c c, $66 c, $66 c, $66 c, $dc c, $00 c,   \  98 b
  $00 c, $00 c, $7c c, $c6 c, $c0 c, $c6 c, $7c c, $00 c,   \  99 c
  $1c c, $0c c, $7c c, $cc c, $cc c, $cc c, $76 c, $00 c,   \ 100 d
  $00 c, $00 c, $7c c, $c6 c, $fe c, $c0 c, $7c c, $00 c,   \ 101 e
  $3c c, $66 c, $60 c, $f8 c, $60 c, $60 c, $f0 c, $00 c,   \ 102 f
  $00 c, $00 c, $76 c, $cc c, $cc c, $7c c, $0c c, $f8 c,   \ 103 g
  $e0 c, $60 c, $6c c, $76 c, $66 c, $66 c, $e6 c, $00 c,   \ 104 h
  $18 c, $00 c, $38 c, $18 c, $18 c, $18 c, $3c c, $00 c,   \ 105 i
  $06 c, $00 c, $06 c, $06 c, $06 c, $66 c, $66 c, $3c c,   \ 106 j
  $e0 c, $60 c, $66 c, $6c c, $78 c, $6c c, $e6 c, $00 c,   \ 107 k
  $38 c, $18 c, $18 c, $18 c, $18 c, $18 c, $3c c, $00 c,   \ 108 l
  $00 c, $00 c, $ec c, $fe c, $d6 c, $d6 c, $d6 c, $00 c,   \ 109 m
  $00 c, $00 c, $dc c, $66 c, $66 c, $66 c, $66 c, $00 c,   \ 110 n
  $00 c, $00 c, $7c c, $c6 c, $c6 c, $c6 c, $7c c, $00 c,   \ 111 o
  $00 c, $00 c, $dc c, $66 c, $66 c, $7c c, $60 c, $f0 c,   \ 112 p
  $00 c, $00 c, $76 c, $cc c, $cc c, $7c c, $0c c, $1e c,   \ 113 q
  $00 c, $00 c, $dc c, $76 c, $60 c, $60 c, $f0 c, $00 c,   \ 114 r
  $00 c, $00 c, $7e c, $c0 c, $7c c, $06 c, $fc c, $00 c,   \ 115 s
  $30 c, $30 c, $fc c, $30 c, $30 c, $36 c, $1c c, $00 c,   \ 116 t
  $00 c, $00 c, $cc c, $cc c, $cc c, $cc c, $76 c, $00 c,   \ 117 u
  $00 c, $00 c, $c6 c, $c6 c, $c6 c, $6c c, $38 c, $00 c,   \ 118 v
  $00 c, $00 c, $c6 c, $d6 c, $d6 c, $fe c, $6c c, $00 c,   \ 119 w
  $00 c, $00 c, $c6 c, $6c c, $38 c, $6c c, $c6 c, $00 c,   \ 120 x
  $00 c, $00 c, $c6 c, $c6 c, $c6 c, $7e c, $06 c, $fc c,   \ 121 y
  $00 c, $00 c, $7e c, $4c c, $18 c, $32 c, $7e c, $00 c,   \ 122 z
  $0e c, $18 c, $18 c, $70 c, $18 c, $18 c, $0e c, $00 c,   \ 123 {
  $18 c, $18 c, $18 c, $18 c, $18 c, $18 c, $18 c, $00 c,   \ 124 |
  $70 c, $18 c, $18 c, $0e c, $18 c, $18 c, $70 c, $00 c,   \ 125 }
  $76 c, $dc c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \ 126 ~
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \ 127 .
  $7c c, $c6 c, $c0 c, $c0 c, $c6 c, $7c c, $18 c, $30 c,   \ 128 .
  $cc c, $00 c, $cc c, $cc c, $cc c, $cc c, $76 c, $00 c,   \ 129 .
  $0c c, $18 c, $7c c, $c6 c, $fe c, $c0 c, $7c c, $00 c,   \ 130 .
  $7c c, $82 c, $78 c, $0c c, $7c c, $cc c, $76 c, $00 c,   \ 131 .
  $c6 c, $00 c, $78 c, $0c c, $7c c, $cc c, $76 c, $00 c,   \ 132 .
  $30 c, $18 c, $78 c, $0c c, $7c c, $cc c, $76 c, $00 c,   \ 133 .
  $38 c, $00 c, $78 c, $0c c, $7c c, $cc c, $76 c, $00 c,   \ 134 .
  $00 c, $00 c, $7c c, $c0 c, $c0 c, $7c c, $30 c, $60 c,   \ 135 .
  $7c c, $82 c, $7c c, $c6 c, $fe c, $c0 c, $7c c, $00 c,   \ 136 .
  $c6 c, $00 c, $7c c, $c6 c, $fe c, $c0 c, $7c c, $00 c,   \ 137 .
  $30 c, $18 c, $7c c, $c6 c, $fe c, $c0 c, $7c c, $00 c,   \ 138 .
  $66 c, $00 c, $38 c, $18 c, $18 c, $18 c, $3c c, $00 c,   \ 139 .
  $7c c, $82 c, $38 c, $18 c, $18 c, $18 c, $3c c, $00 c,   \ 140 .
  $30 c, $18 c, $00 c, $38 c, $18 c, $18 c, $3c c, $00 c,   \ 141 .
  $c6 c, $38 c, $6c c, $c6 c, $fe c, $c6 c, $c6 c, $00 c,   \ 142 .
  $38 c, $00 c, $7c c, $c6 c, $fe c, $c6 c, $c6 c, $00 c,   \ 143 .
  $18 c, $30 c, $fe c, $c0 c, $f8 c, $c0 c, $fe c, $00 c,   \ 144 .
  $00 c, $00 c, $7e c, $18 c, $7e c, $d8 c, $7e c, $00 c,   \ 145 .
  $3e c, $6c c, $cc c, $fe c, $cc c, $cc c, $ce c, $00 c,   \ 146 .
  $7c c, $82 c, $7c c, $c6 c, $c6 c, $c6 c, $7c c, $00 c,   \ 147 .
  $c6 c, $00 c, $7c c, $c6 c, $c6 c, $c6 c, $7c c, $00 c,   \ 148 .
  $30 c, $18 c, $7c c, $c6 c, $c6 c, $c6 c, $7c c, $00 c,   \ 149 .
  $78 c, $84 c, $00 c, $cc c, $cc c, $cc c, $76 c, $00 c,   \ 150 .
  $60 c, $30 c, $cc c, $cc c, $cc c, $cc c, $76 c, $00 c,   \ 151 .
  $c6 c, $00 c, $c6 c, $c6 c, $c6 c, $7e c, $06 c, $fc c,   \ 152 .
  $c6 c, $38 c, $6c c, $c6 c, $c6 c, $6c c, $38 c, $00 c,   \ 153 .
  $c6 c, $00 c, $c6 c, $c6 c, $c6 c, $c6 c, $7c c, $00 c,   \ 154 .
  $18 c, $18 c, $7e c, $c0 c, $c0 c, $7e c, $18 c, $18 c,   \ 155 .
  $38 c, $6c c, $64 c, $f0 c, $60 c, $66 c, $fc c, $00 c,   \ 156 .
  $66 c, $66 c, $3c c, $7e c, $18 c, $7e c, $18 c, $18 c,   \ 157 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \ 158 .
  $00 c, $1c c, $36 c, $30 c, $fc c, $30 c, $30 c, $78 c,   \ 159 .
  $18 c, $30 c, $78 c, $0c c, $7c c, $cc c, $76 c, $00 c,   \ 160 .
  $0c c, $18 c, $00 c, $38 c, $18 c, $18 c, $3c c, $00 c,   \ 161 .
  $0c c, $18 c, $7c c, $c6 c, $c6 c, $c6 c, $7c c, $00 c,   \ 162 .
  $18 c, $30 c, $cc c, $cc c, $cc c, $cc c, $76 c, $00 c,   \ 163 .
  $76 c, $dc c, $00 c, $dc c, $66 c, $66 c, $66 c, $00 c,   \ 164 .
  $76 c, $dc c, $00 c, $e6 c, $f6 c, $de c, $ce c, $00 c,   \ 165 .
  $3c c, $6c c, $6c c, $3e c, $00 c, $7e c, $00 c, $00 c,   \ 166 .
  $38 c, $6c c, $6c c, $38 c, $00 c, $7c c, $00 c, $00 c,   \ 167 .
  $18 c, $00 c, $18 c, $18 c, $30 c, $63 c, $3e c, $00 c,   \ 168 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \ 169 .
  $00 c, $00 c, $00 c, $fe c, $06 c, $06 c, $00 c, $00 c,   \ 170 .
  $63 c, $e6 c, $6c c, $7e c, $33 c, $66 c, $cc c, $0f c,   \ 171 .
  $63 c, $e6 c, $6c c, $7a c, $36 c, $6a c, $df c, $06 c,   \ 172 .
  $18 c, $00 c, $18 c, $18 c, $3c c, $3c c, $18 c, $00 c,   \ 173 .
  $00 c, $33 c, $66 c, $cc c, $66 c, $33 c, $00 c, $00 c,   \ 174 .
  $00 c, $cc c, $66 c, $33 c, $66 c, $cc c, $00 c, $00 c,   \ 175 .
  $22 c, $88 c, $22 c, $88 c, $22 c, $88 c, $22 c, $88 c,   \ 176 .
  $55 c, $aa c, $55 c, $aa c, $55 c, $aa c, $55 c, $aa c,   \ 177 .
  $77 c, $dd c, $77 c, $dd c, $77 c, $dd c, $77 c, $dd c,   \ 178 .
  $18 c, $18 c, $18 c, $18 c, $18 c, $18 c, $18 c, $18 c,   \ 179 .
  $18 c, $18 c, $18 c, $18 c, $f8 c, $18 c, $18 c, $18 c,   \ 180 .
  $18 c, $18 c, $18 c, $18 c, $f8 c, $18 c, $18 c, $18 c,   \ 181 .
  $18 c, $18 c, $18 c, $18 c, $f8 c, $18 c, $18 c, $18 c,   \ 182 .
  $00 c, $00 c, $00 c, $00 c, $f8 c, $18 c, $18 c, $18 c,   \ 183 .
  $00 c, $00 c, $00 c, $00 c, $f8 c, $18 c, $18 c, $18 c,   \ 184 .
  $18 c, $18 c, $18 c, $18 c, $f8 c, $18 c, $18 c, $18 c,   \ 185 .
  $18 c, $18 c, $18 c, $18 c, $18 c, $18 c, $18 c, $18 c,   \ 186 .
  $00 c, $00 c, $00 c, $00 c, $f8 c, $18 c, $18 c, $18 c,   \ 187 .
  $18 c, $18 c, $18 c, $18 c, $f8 c, $00 c, $00 c, $00 c,   \ 188 .
  $18 c, $18 c, $18 c, $18 c, $f8 c, $00 c, $00 c, $00 c,   \ 189 .
  $18 c, $18 c, $18 c, $18 c, $f8 c, $00 c, $00 c, $00 c,   \ 190 .
  $00 c, $00 c, $00 c, $00 c, $f8 c, $18 c, $18 c, $18 c,   \ 191 .
  $18 c, $18 c, $18 c, $18 c, $1f c, $00 c, $00 c, $00 c,   \ 192 .
  $18 c, $18 c, $18 c, $18 c, $ff c, $00 c, $00 c, $00 c,   \ 193 .
  $00 c, $00 c, $00 c, $00 c, $ff c, $18 c, $18 c, $18 c,   \ 194 .
  $18 c, $18 c, $18 c, $18 c, $1f c, $18 c, $18 c, $18 c,   \ 195 .
  $00 c, $00 c, $00 c, $00 c, $ff c, $00 c, $00 c, $00 c,   \ 196 .
  $18 c, $18 c, $18 c, $18 c, $ff c, $18 c, $18 c, $18 c,   \ 197 .
  $18 c, $18 c, $18 c, $18 c, $1f c, $18 c, $18 c, $18 c,   \ 198 .
  $18 c, $18 c, $18 c, $18 c, $1f c, $18 c, $18 c, $18 c,   \ 199 .
  $18 c, $18 c, $18 c, $18 c, $1f c, $00 c, $00 c, $00 c,   \ 200 .
  $00 c, $00 c, $00 c, $00 c, $1f c, $18 c, $18 c, $18 c,   \ 201 .
  $18 c, $18 c, $18 c, $18 c, $ff c, $00 c, $00 c, $00 c,   \ 202 .
  $00 c, $00 c, $00 c, $00 c, $ff c, $18 c, $18 c, $18 c,   \ 203 .
  $18 c, $18 c, $18 c, $18 c, $1f c, $18 c, $18 c, $18 c,   \ 204 .
  $00 c, $00 c, $00 c, $00 c, $ff c, $00 c, $00 c, $00 c,   \ 205 .
  $18 c, $18 c, $18 c, $18 c, $ff c, $18 c, $18 c, $18 c,   \ 206 .
  $18 c, $18 c, $18 c, $18 c, $ff c, $00 c, $00 c, $00 c,   \ 207 .
  $18 c, $18 c, $18 c, $18 c, $ff c, $00 c, $00 c, $00 c,   \ 208 .
  $00 c, $00 c, $00 c, $00 c, $ff c, $18 c, $18 c, $18 c,   \ 209 .
  $00 c, $00 c, $00 c, $00 c, $ff c, $18 c, $18 c, $18 c,   \ 210 .
  $18 c, $18 c, $18 c, $18 c, $1f c, $00 c, $00 c, $00 c,   \ 211 .
  $18 c, $18 c, $18 c, $18 c, $1f c, $00 c, $00 c, $00 c,   \ 212 .
  $00 c, $00 c, $00 c, $00 c, $1f c, $18 c, $18 c, $18 c,   \ 213 .
  $00 c, $00 c, $00 c, $00 c, $1f c, $18 c, $18 c, $18 c,   \ 214 .
  $18 c, $18 c, $18 c, $18 c, $ff c, $18 c, $18 c, $18 c,   \ 215 .
  $18 c, $18 c, $18 c, $18 c, $ff c, $18 c, $18 c, $18 c,   \ 216 .
  $18 c, $18 c, $18 c, $18 c, $f8 c, $00 c, $00 c, $00 c,   \ 217 .
  $00 c, $00 c, $00 c, $00 c, $1f c, $18 c, $18 c, $18 c,   \ 218 .
  $ff c, $ff c, $ff c, $ff c, $ff c, $ff c, $ff c, $ff c,   \ 219 .
  $00 c, $00 c, $00 c, $00 c, $ff c, $ff c, $ff c, $ff c,   \ 220 .
  $f0 c, $f0 c, $f0 c, $f0 c, $f0 c, $f0 c, $f0 c, $f0 c,   \ 221 .
  $0f c, $0f c, $0f c, $0f c, $0f c, $0f c, $0f c, $0f c,   \ 222 .
  $ff c, $ff c, $ff c, $ff c, $00 c, $00 c, $00 c, $00 c,   \ 223 .
  $78 c, $cc c, $cc c, $d8 c, $cc c, $c6 c, $cc c, $00 c,   \ 224 .
  $78 c, $cc c, $cc c, $d8 c, $cc c, $c6 c, $cc c, $00 c,   \ 225 .
  $18 c, $18 c, $18 c, $18 c, $1f c, $18 c, $18 c, $18 c,   \ 226 .
  $00 c, $fe c, $00 c, $fe c, $00 c, $fe c, $00 c, $00 c,   \ 227 .
  $36 c, $36 c, $36 c, $36 c, $3f c, $00 c, $00 c, $00 c,   \ 228 .
  $0c c, $18 c, $30 c, $18 c, $0c c, $00 c, $7e c, $00 c,   \ 229 .
  $00 c, $00 c, $66 c, $66 c, $66 c, $66 c, $7c c, $c0 c,   \ 230 .
  $0e c, $1b c, $1b c, $18 c, $18 c, $18 c, $18 c, $18 c,   \ 231 .
  $00 c, $00 c, $00 c, $00 c, $3f c, $36 c, $36 c, $36 c,   \ 232 .
  $36 c, $36 c, $37 c, $30 c, $3f c, $00 c, $00 c, $00 c,   \ 233 .
  $18 c, $18 c, $18 c, $18 c, $f8 c, $00 c, $00 c, $00 c,   \ 234 .
  $fe c, $c6 c, $60 c, $30 c, $60 c, $c6 c, $fe c, $00 c,   \ 235 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \ 236 .
  $00 c, $18 c, $00 c, $7e c, $00 c, $18 c, $00 c, $00 c,   \ 237 .
  $00 c, $00 c, $7e c, $d8 c, $d8 c, $d8 c, $70 c, $00 c,   \ 238 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \ 239 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \ 240 .
  $18 c, $18 c, $7e c, $18 c, $18 c, $00 c, $7e c, $00 c,   \ 241 .
  $60 c, $30 c, $18 c, $30 c, $60 c, $00 c, $78 c, $00 c,   \ 242 .
  $18 c, $30 c, $60 c, $30 c, $18 c, $00 c, $78 c, $00 c,   \ 243 .
  $08 c, $14 c, $10 c, $10 c, $10 c, $10 c, $10 c, $10 c,   \ 244 .
  $10 c, $10 c, $10 c, $10 c, $10 c, $50 c, $20 c, $00 c,   \ 245 .
  $00 c, $18 c, $00 c, $7e c, $00 c, $18 c, $00 c, $00 c,   \ 246 .
  $00 c, $00 c, $64 c, $98 c, $00 c, $64 c, $98 c, $00 c,   \ 247 .
  $38 c, $6c c, $6c c, $38 c, $00 c, $00 c, $00 c, $00 c,   \ 248 .
  $00 c, $00 c, $00 c, $30 c, $30 c, $00 c, $00 c, $00 c,   \ 249 .
  $00 c, $00 c, $00 c, $18 c, $00 c, $00 c, $00 c, $00 c,   \ 250 .
  $1f c, $10 c, $10 c, $90 c, $50 c, $30 c, $10 c, $00 c,   \ 251 .
  $a0 c, $d0 c, $90 c, $90 c, $90 c, $00 c, $00 c, $00 c,   \ 252 .
  $78 c, $0c c, $18 c, $30 c, $7c c, $00 c, $00 c, $00 c,   \ 253 .
  $00 c, $00 c, $3c c, $3c c, $3c c, $3c c, $00 c, $00 c,   \ 254 .
  $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c, $00 c,   \ 255 .

\ Select this font: hand its table and 8x8 cell size to the
\ engine, which works out the row stride. Call `vga-8x8` again any time to
\ switch back to it after another font has been loaded.
: vga-8x8 ( -- )  (vga-8x8) 8 8 font! ;
vga-8x8          \ make it the current font as soon as this file loads
